# Generated by Django 2.2 on 2021-02-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0002_auto_20210226_1537'),
        ('auth', '0001_initial'),
        ('reversion', '0002_auto_20210226_1537'),
        ('admin', '0003_auto_20210226_1537'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
